#!/bin/bash 

cd `cat ~/.git_root`
project=$1
if [[ $project = *[!\ ]* ]]; then
  echo "recording note for project " $project
else
  echo "no project entered aborting"
  exit 1;
fi
cd $project
git config --global core.editor "/usr/bin/gedit"
date > .update-${project}
git add .
git commit
~/bin/push_project ${project}